rpm-software-management/tito

tito.spec

Use unversioned macros for EL6, don't reset python_sitelib on F22+ and
always use the Python binary determined for the OS, not python3 for the
shebang line.
Fixes #167, #168 
---
Successful builds at http://copr-fe.cloud.fedoraproject.org/coprs/domcleal/tito-nightly/build/87119/, though I've only tested the EL6 RPM and visually inspected the rawhide RPM.

Fixes macro initialisation on EL6, F22+

---

README.mkd

tito is an easily discovered tool when looking for information on rpm packaging, especially SCM integration.
There are now some useful related tools, like mock's SCM integration, mockchain, Koji, fedpkg, etc that are not especially easily discovered by new packagers. Making these more visible by documenting them in tito's README would be a help to new packagers.

Help new packagers find tools related to tito

---

src/tito/builder/main.py
test/functional/builder_tests.py

Instead of being a command line-only option, the string of extra rpmbuild
arguments can now be passed in via the general builder args mechanism, so it
can even be configured from releasers.conf.
Fixes #155

Allow override of rpmbuild_options from builder arguments

---

share/tito_completion.sh
tito.spec

Here's an initial go at getting some bash-completion for the tito command.
Module options are a union of those culled from both "tito MODULE --help" and
"man tito" -- there are discrepancies.  Some options were deliberately omitted
such as those documented as deprecated or "avoid using this please".  All
short options are also omitted as their completion would not save any typing
but would hinder the accessibility of the longer options.

bash-completion for tito command

---

README.mkd
doc/builders.mkd
rel-eng/tito.props
src/tito/builder/main.py
src/tito/cli.py
src/tito/common.py
src/tito/config_object.py
src/tito/tagger/main.py
test/functional/fetch_tests.py
test/functional/fixture.py
test/functional/multiproject_tests.py
test/functional/release_yum_tests.py
test/functional/singleproject_tests.py
tito.8.asciidoc
tito.props.5.asciidoc

if /releng is present it will be used. Otherwise /.tito will be used.
The patch is surprisingly small. With major changes in documentation.
I decided to not declare /rel-eng/ as obsolete and ask people for rename as I would like to see this function for at least one release before we call /rel-eng/ obsolete (if ever).

substitute /releng for /.tito #161

---

src/tito/release/distgit.py
titorc.5.asciidoc

Specifying these values on .titorc will allow to use tito without having to create a specific username in Linux for it, in case your username in git is different than the one on your computer.

Add RHPKG/FEDPKG_USER to be passed to rh/fedpkg

---

src/tito/tagger/main.py

Merge commits rarely add value to the RPM changelog.  This patch removes
lines from the changelog that begin with "Merge pull request" or "Merge
remote-tracking" or "Merge branch".  The old behavior can be restored
by setting "keep_merge_commits" to 1.

Filter lines beginning with "Merge" from the changelog.

---

src/tito/builder/main.py
test/functional/builder_tests.py

3892359 changed builder args to always be arrays, so concatenation of
rpmbuild options with other strings then failed.
File "/usr/lib/python2.7/site-packages/tito/release/main.py", line 530, in _koji_release
builder.srpm(dist=disttag)
File "/usr/lib/python2.7/site-packages/tito/builder/main.py", line 210, in srpm
rpmbuild_options = self.rpmbuild_options + self._scl_to_rpmbuild_option()
TypeError: can only concatenate list (not "str") to list
Change builder args to be joined by a single space, allowing multiple
arguments to be passed in.

Fix rpmbuild_options array handling from builder args

---

src/tito/builder/main.py
src/tito/common.py

To get rid of:
Yum-utils package has been deprecated, use dnf instead.
See 'man yum2dnf' for more information.

Ask user to run DNF instead of YUM

---

src/tito/common.py
src/tito/release/copr.py
src/tito/release/main.py
test/functional/release_copr_tests.py
titorc.5.asciidoc

By using a user specific URL, multiple members of the same team can
submit Copr releases without having to share credentials to the SRPM
remote location.  For example, each member of the team can set
COPR_REMOTE_LOCATION in .titorc to their <username>.fedorapeople.org
space.
The URL defined in the releaser will take precedence.

Allow a user specific Copr remote SRPM URL.

---

src/tito/tagger/rheltagger.py

Use _changelog_format() instead of _changelog_email() which no longer
exists.

Fix changelog format function name

---

releasers.conf.5.asciidoc
src/tito/release/copr.py
test/functional/release_copr_tests.py

Additionally to the current `CoprReleaser` behavior in which the builded SRPM is uploaded to remote server and then submitted to the Copr via URL, I have implemented direct approach for submitting the package from your local storage right into the Copr. This feature is supported since `python-copr-1.58-1`.
With this patch it's supported the old style configuration:
[copr]
releaser = tito.release.CoprReleaser
project_name = foo
upload_command = scp %(srpm)s user@example.com:/home/user/public_html/
remote_location = http://example.com/~user/
as well as the:
[copr]
releaser = tito.release.CoprReleaser
project_name = foo
Can you review it @xsuchy and give me your blessing? :-)

Add possibility to upload SRPM directly to Copr

---

releasers.conf.5.asciidoc
src/tito/release/copr.py

This adds the ability to add 'copr-cli build' options to the releasers.conf file for the copr releaser.
My team will use this specifically for --nowait so that we can submit builds and move on.
This could be useful for the other options, like --memory, --chroot, --timeout, etc.
Here is an example releasers.conf file that works:
```
[copr-openshift-tools]
releaser = tito.release.CoprReleaser
project_name = openshift-tools
build_options = --nowait
```
Not specifying build_options in the config file also works (it's completely optional).

Added ability to pass extra copr-cli build options to the copr releaser.

---

src/tito/builder/main.py

In some cases, we aren't always assured that the releaser will return
us back to proper directory to re-lock the git annex file. This is
the case with the DistGitBuilder for example. This ensures we store
and return to the proper directory before issuing the lock on cleanup

Ensure GitAnnexBuilder cleanup returns to proper directory

---

src/tito/common.py

Reason of this pull request is described in the issue #196.
Since there is comment `Returns only the file name, rather than the full path.` in `find_spec_file` function, I think the proposed change is ok. If there is some problem with it, I would propose just this:
diff --git a/src/tito/builder/main.py b/src/tito/builder/main.py
index 5819631..5b1e995 100644
--- a/src/tito/builder/main.py
+++ b/src/tito/builder/main.py
@@ -248,7 +248,7 @@ def rpm(self):
if re.search('Failed build dependencies', err.output):
cmd = "dnf builddep %s" if package_manager() == "dnf" else "yum-builddep %s"
msg = "Please run '%s' as root." % \
-                    cmd % find_spec_file(self.relative_project_dir)
+                    cmd % find_spec_file(os.path.basename(self.relative_project_dir))
error_out('%s' % …

Suggest correct path when spec is in subdirectory; Fix #196

---

src/tito/tagger/main.py

An oversight on my part during all the Mead work.

Tagging with --use-version did not work with Mead projects.

---

tito.spec

This was added in commit 9ce944264222d24558d9fb72d9684a267189895a and is not actually needed.
We have it just because we print
Failed build dependencies
Please run 'yum-builddep %s' as root.
So it should be rather replaced by:
Suggest: yum-utils
But that cannot be parsed on el6 and is in fact not needed on F23+ at all.
So it should be rather described by rich deps like
Suggest: (yum-utils if yum) and (dnf-plugins-core if dnf)
But rich deps should not be used for now.
So lets remove it for now. So yum-utils can be safely retired in rawhide.

remove dependency on yum-utils

---

src/tito/common.py

If package is unttaged and you build it with --test then previously 0 was used as number of commits
since last tag.
This results in packages which has no upgrade path.
With this patch it use number of commits since initial commit, which is growing number.
Therefore packages can be upgraded without usage of --force.

better release number for untagged packages

---

src/tito/tagger/main.py
test/functional/singleproject_tests.py
tito.props.5.asciidoc

Fixes #228.
I did not find a better way to change the configuration in tests. Please let me know if I should rework it.

Allow customizing git commit message

---

src/tito/tagger/main.py

Instead of special-casing the case where a user has supplied
the specific version to use, we can instead use the same version
tagger for both cases and detect inside of that tagger whether
or not the user has supplied the tag.
Signed-off-by: Steve Kuznetsov skuznets@redhat.com

Don't use a special tagger for the `--use-version` case

---

tito.props.5.asciidoc

The documentation for taggers should not mention builders.

Fix errors in documentation

---

src/tito/tagger/main.py

This will create description as:
Automatic commit of package [tito] release [0.6.9-1].
Created by command:
/usr/bin/tito tag
It use the feature of git-commit that additional -m option are used as next paragraph.
This can help newbies to identify tool and process how tagging was actually done (for example usage of --keep-version).

explain how automatic tagging was done

---

hacking/runtests.sh

To allow the tests to run from a host with SELinux enabled, the data
needs to be relabeled to the correct SELinux contexts. Adding the `Z`
label to the volume mount allows for this to occur.

Relabel test container volume contents for SELinux

---

hacking/titotest-fedora-rawhide/Dockerfile

Use `dnf` instead of `yum` in Fedora Rawhide tests

---

src/tito/common.py

Using `def` instead of `x = lambda...` satisfies the PEP8 E731 warning.
@dgoodwin all tests now pass

Use `def` instead of a lambda for function assignment

---

runtests.py
src/tito/cli.py
src/tito/tagger/main.py
test/functional/fixture.py
test/functional/singleproject_tests.py

When multiple tags exist for one version of a project, or when a version
is passed to `tito tag --use-version` that does not exactly correspond
with a tag in the repository's git history, the auto-generated release
is not guaranteed to monotonically increase. In order for users to
overcome this issue without building complicated logic into `tito`, it
is simpler to allow users to provide a literal release string to use.
---
The logic that previously existed for updating the version and/or the
release in the specfile contained a lot of repetition and enough boolean
logic that it was becoming hard to read. By simplifying that stanza, the
hope is that the resulting code is easier to understand.
Signed-off-by: Steve Kuznetsov …

Added `--use-release` flag for `tito tag`

---

README.md

From the looks of it, the `globalconfig` section is deprecated and
adding anything to that section of `tito.props` results in an error:
WARNING: Please rename [globalconfig] to [buildconfig] in tito.props
/cc @dgoodwin

Rename `globalconfig` section to `buildconfig` in README

---

src/tito/cli.py

In 26b02a7, the utility of the `ForceVersionTagger` was merged with the
base `VersionTagger`, so it is no longer necessary to ever explicitly
invoke the `ForceVersionTagger` class. Furthermore, the `elif` and
`else` branches of the decision tree for the tagger class were identical
in the previous implementation, so they were collapsed as well. The
remaining tagger class assignment is a simple query of the `tito.props`
file.

Collapse tagger class selection logic

---

src/tito/builder/main.py
src/tito/cli.py
tito.8.asciidoc

When using `tito build --install` on a system without `sudo`, such as
inside of a Linux container build, the current implementation fails.
Furthermore, if the user is running `tito build --install` with the
correct level of privilege, it is not necessary to escalate privileges
further for the installation step.
This patch adds the `--dont-escalate-privileges` flag to `tito build`
and defaults it to `True`, which keeps the behavior backwards compat-
ible. Users will want to use this flag when building RPMs inside of a
container or when running `tito build` with the requisite permissions
for installing in the first place.

Added an option to not escalate privileges on `tito build --install`

---

src/tito/builder/main.py

When a custom implementation of a tito Tagger is used, the mapping
function that is used to generate a tag from a version in the custom
Tagger must also be used in whichever tito Builder is used on that
repository. This commit factors out the mapping of version to tag so
that custom implementations of a Builder can inject custom logic here
with minimal effort, as is possible on the tito.VersionTagger by
overriding the _get_new_tag() function.

Factor out the version->tag mapping in the Builder

---

src/tito/builder/main.py
src/tito/common.py

Improved debugging for RPM build step
---
Print command debugging information only once
When debugging is turned on and a command is run that fails or with
`print_on_success` on, the output for the command execution ends up
being printed twice. This change ensures that only one set of output
is printed at any point.
---

Updated some debugging statements

---

src/tito/common.py

When using `$DEBUG=1`, often the output from different parts of `tito`
that output to different streams (for instance, `stderr` and `stdout`)
appears in the terminal in a garbled order. Furthermore, the stacktraces
generated by the Python interpreter are out of order with the output
from the `tito` process and often fragmented. By flushing the output
buffers on `tito.common._out()` we should be able to work around this.

Flush output buffers

---

hacking/runtests.sh
src/tito/builder/main.py
src/tito/common.py
src/tito/tagger/main.py

Only flush output stream if flushing is supported
While file handles support the `.flush()` method, some of the more
UNIX-ey pipes and tees do not. We should try to `.flush()` when we
can, but not bother when we can't.
---
Added support for choosing platforms for tests
Running the entire suite of containerized tests across all of the
platforms that are supported takes quite a while, especially if the
container images need to be built. Now, the platforms that are to be
tested can be specified with `$PY2_DISTROS` and `$PY3_DISTROS`.
---
Refactored version->tag mapping logic in Tagger
While the `tito.VersionTagger._get_new_tag()` method encapsulated some
of the version->tag mapping …

Refactored version->tag mapping logic in Tagger

---

src/tito/builder/main.py
src/tito/cli.py
tito.8.asciidoc

Refactor `rpmbuild` invocation for readability
---
Added `--quiet` and `--verbose` to `tito build`
The current output levels from `tito build` are both very verbose in the
case that nothing goes wrong and often missing full context when some-
thing does go wrong. By exposing `--quiet` and `--verbose`, the build
process should be able to modulate the amount of output coming from the
internal process and from `rpmbuild`.
---

Added `--quiet` and `--verbose` to `tito build`

---

hacking/titotest-fedora-rawhide/Dockerfile

Fixes https://github.com/dgoodwin/tito/issues/247 
Rawhide tests run fine now, with the one test failure being 
```
======================================================================
FAIL: test_conformance (unit.pep8_tests.TestPep8)
----------------------------------------------------------------------
Traceback (most recent call last):
File "/home/sandbox/test/unit/pep8_tests.py", line 70, in test_conformance
self.fail("Found PEP8 errors that may break your code in Python 3:\n%s" % output)
AssertionError: Found PEP8 errors that may break your code in Python 3:
1       E731 do not assign a lambda expression, use a def
-------------------- >> begin captured stdout << ---------------------
Testing in: /home/sandbox/test/unit/../.. …
```

Work around `dnf` issues and install builddep for Rawhide

---

MANIFEST.in
src/tito/builder/main.py
src/tito/cli.py

Achieve quiet output from `rpmbuild` without passing `--quiet`
The output from `rpmbuild` is necessary to capture for determining which
artifacts were created as part of the build, so we cannot achieve quiet
output from `tito build --quiet` by passing `--quiet` to `rpmbuild` as
well. Instead we just don't print the output from the command unless it
fails.
---
Update the MANIFEST.in
No `README.mkd` file exists, but `README.md` does. No files ending in
`.5` exist, but some manpages that end in `.5.asciidoc` do.
---
Correctly pass verbosity options through the builder CLI
---
Use correct print-formatting directive in debugging …

Updates to the MANIFEST and `tito build --quiet`

---

src/tito/builder/main.py
src/tito/common.py
src/tito/tagger/main.py
test/functional/singleproject_tests.py

Use `.assertTrue()` instead of `.assertIn()`
CentOS 6 only has Python 2.6 available, on which the unit testing
frameworks do not expose a `.assertIn()` helper method. Instead, we can
use `.assertTrue(x in y)`.
---
Only use `rpmbuild --noclean` if it is supported
CentOS 6 only has rpmbuild 4.8 available, on which the `--noclean` option
is not present. We should only pass `--noclean` to `rpmbuild` when we
can determine that it is supported.
---
Explicitly define indicies in formatting statements
Python 2.6 is the latest Python version available on CentOS 6. In Python
2.6, the newer formatting statements must have indexed formatting
specifiers, so you must write
"{0}{1}".format(foo, bar) …

Iron out Python 2.6 incompatibilities for CentOS 6

---

src/tito/common.py

When using `tito tag --undo` in a repository with a dirty
`git` state, no action should be taken.

Do not undo tags when git state is dirty

---

src/tito/cli.py

Previously, the `optparse` option parsing was not being done in the
call to `tito init`, which led to CLI invocations that used `--help`
not getting the helptext and instead getting the normal output of
`tito init`.

Parse options in `tito init`

---

src/tito/tagger/main.py
test/functional/custom_tag_tests.py
tito.props.5.asciidoc

`VersionTagger` creates a long tag - e.g. `project-1.0-3` - but its not required for most projects. This PR adds a new tagger which creates `<version>` tag, which would fit most projects.
TODO:

VersionTagger support for custom tag format

---

src/tito/builder/main.py
src/tito/tagger/main.py
test/functional/custom_tag_tests.py

A follow-up for https://github.com/dgoodwin/tito/pull/277 - `tito release` should also understand the new tag format

Custom tag support in tito release

---

src/tito/builder/main.py

When building a large number of packages, the current output from tito
will place all of them on one very long line, which makes it hard to
read. Instead, we should place them on separate lines to format them
more like a list.
/cc @dgoodwin PTAL

Format package list more cleanly

---

src/tito/common.py

addressing:
Python runtime initialized with LC_CTYPE=C (a locale with default ASCII encoding), which may cause Unicode compatibility problems. Using C.UTF-8, C.utf8, or UTF-8 (if available) as alternative Unicode-compatible locales is recommended.

use LC_ALL=C.UTF-8 rather than plain C

---

src/tito/tagger/main.py
test/functional/multiproject_tests.py

This adds `--use-version` support to `ReleaseTagger` as discussed in #274 and #283.
Basically it just checks if the user passed `--use-version` and calls `_bump_version` with either `release=True` or `release=False` based on that.

ReleaseTagger --use-version support

---

src/tito/common.py
test/unit/common_tests.py

When doing --test build, if the spec file 'Release' line contains no '%{?dist}' part, tito will append 'None' at the end of the release option. This change makes sure nothing is added when this part is not present in the line.

Don't append 'None' to Release line with no '%{?dist}' part

---

src/tito/cli.py

When doing concurrent build, if `/tmp/tito` doesn't exist, even if different output
directories for different builds are specified,
tito will fail because tito processes are trying to create
`/tmp/tito` at the time that directory doesn't exist.
Here is the stack trace when this issue occurs:
```
06:42:15 [el7] + tito build --test --rpm --output=artifacts/el7 --builder=tito.builder.MockBuilder --arg=mock=eng-rhel-7-candidate-x86_64
06:42:16 [el7] ERROR: Error running command: mkdir /tmp/tito
06:42:16 [el7]
06:42:16 [el7] Status code: 256
06:42:16 [el7]
06:42:16 [el7] Command output: mkdir: cannot create directory '/tmp/tito': File exists
06:42:16 [el7]
06:42:16 [el7] Creating output directory: /tmp/tito
06:42:16 [el7] Traceback (most recent call last):
06:42:16 [el7]   File …
```

Fix a race condition when /tmp/tito doesn't exist

---

README.md

Links at the bottom of README.md file are not clickable (raw markdown is displayed instead of HTML). This commit fixes that.
Additionally, typo in "Related Projects" section is fixed

Fix links in README.md file

---

src/tito/common.py
src/tito/tagger/main.py

git push knows --follow-tags option since 1.8.3 (released in April 2013). It pushes both new commits and tags associated with them (if any) in one transaction. It was introduced as preferred way of doing `git push && git push --tags`.
This commit changes user-visible messages to encourage people to use this option instead of old idiom.

Encourage usage of git push --follow-tags

---

src/tito/release/distgit.py
tito.props.5.asciidoc

remote_git_name now works in releasers.conf as intended.

Fixing remote_git_name

---

src/tito/builder/main.py

According to mock man page the default behavior without a command flag is to run --rebuild.
This change avoids what is essentially doing --rebuild twice.
```
--rebuild
If no command is specified, rebuild is assumed. Rebuild the specified SRPM(s). The chroot (including the results directory) is cleaned first, unless --no-clean is specified.
```

Avoid double builds with mock

---

src/tito/builder/main.py

Had the following failure after upgrading to tito 0.6.11 and mock 1.4.9 on CentOS7 building CentOS5 packages, I guessed that possibly the file glob wasn't being interpreted by the external command, changing the relevant code to use shutil.copy2 instead resolved the issue.  I didn't figure out why this behavior changed but it would seem that using the built-in file copy support is generally better than forking cp.  HTH
```
Traceback (most recent call last):
File "/bin/tito", line 23, in <module>
CLI().main(sys.argv[1:])
File "/usr/lib/python2.7/site-packages/tito/cli.py", line 203, in main
return module.main(argv)
File "/usr/lib/python2.7/site-packages/tito/cli.py", line 598, in main
scratch=self.options.scratch)
File "/usr/lib/python2.7/site-packages/tito/release/main.py", line 264, in …
```

use built-in shutil.copy2 instead of relying external cp file globbing

---

src/tito/release/distgit.py
src/tito/tagger/__init__.py
src/tito/tagger/susetagger.py
tito.8.asciidoc
tito.props.5.asciidoc

SUSE-style RPM packaging generally prefers having the RPM changelog detached from the main RPM spec file as a changes file. This file is typically named `<pkg>.changes` (corresponding to `<pkg>.spec`).
At package build time in the Open Build Service, the content of the changes file is reformatted to the RPM changelog structure and appended to the spec file by the build system before `rpmbuild` processes it.
This change adds support for this particular workflow, which is common in communities using an instance of the Open Build Service, such as (open)SUSE.
This was originally authored by @mcalmer. The code was ported to work on Python 3 and adapted for the current tito codebase by @Conan-Kudo.

Add support for SUSE-style detached changelogs

---

README.md

Apostrophes aren't for pluralization.  Let's avoid that.

Don't pluralize with apostrophes

---

src/tito/release/main.py

- `tests/` is part of Fedora's Standard Test Interface (see https://fedoraproject.org/wiki/CI/Standard_Test_Interface )
- `gating.yaml` is part of Fedora's CI/Gating (see https://fedoraproject.org/wiki/CI/Gating )

Do not touch tests/ or gating.yaml in dist-git

---

src/tito/tagger/main.py
tito.props.5.asciidoc

Add 'sign_tag = 1' to the [buildconfig] section of tito.props to enable it.

Enable GnuPG signed tags

---

tito.spec

one minor and one which allows to install tito on Fedora 31+

two bugfixes to spec file

---

tito.spec

I found several downstream patches here
https://src.fedoraproject.org/rpms/tito/commits/f31
Without them, tito is not installable (because of `fedora-cert`, but I've applied them all).

Merge downstream patches

---

hacking/titotest-centos-6/Dockerfile
hacking/titotest-centos-7/Dockerfile
hacking/titotest-fedora-27/Dockerfile
hacking/titotest-fedora-rawhide/Dockerfile
requirements.txt
setup.py
src/tito/common.py
test/unit/common_tests.py
tito.spec

As python-blessings is unmaintained nowadays and is not packaged for
EPEL 8, it might be good to move to an active fork.
Related: https://bugzilla.redhat.com/show_bug.cgi?id=1777377

Move to python-blessed

---

hacking/runtests.sh
hacking/titotest-centos-6/Dockerfile
hacking/titotest-fedora-rawhide/Dockerfile
test/functional/fetch_tests.py
test/functional/multiproject_tests.py
test/functional/release_yum_tests.py
test/unit/pep8_tests.py
tito.spec

Our Travis CI currently fails because:
- We are testing python2 on Fedora rawhide - there is no python2 support for a long time
- `python3-pep8` is retired and replaced with `python3-pycodestyle`
- A lot of failing PEP8 checks, that I currently have no time to fix, so I am temporarily disabling them.

Fix travis

---

tito.spec

Fixing this build error
line 40: cd: tito-tito-0.6.12: No such file or directory
We don't need the weird directory naming because it is possible to
pass an optional part of the URL specifying the targeted filename.
See https://fedoraproject.org/wiki/Packaging:SourceURL#Git_Tags

Fix the Source0 URL and prep phase

---

src/tito/common.py
test/unit/common_tests.py

before this, packages with a name like "foo-1-setup" would be end up
parsed as "foo" and confused the heck out of the whitelisting code.
~~the new regex is less greedy about numbers by expecting the tag to end
in something that looks like a version (any number of numbers, dots and
hyphens) followed by an optional "dash anything" for the release.~~
split tag instead of parsing it using a regex as nothing says that the version number must start with a number as seen in the gpg-pubkey packages in Fedora:
gpg-pubkey-facb00b1-570a8081

make get_project_name more resilient

---

src/tito/builder/main.py

Do not run external ls -lR command to debug directory content
When running tests for fedora rawhide in Travis, this debug line
fails with following error:
Command output: ls: cannot access
'/tmp/tmpjw15wzfs-titotest/rpmbuild-titotestpkg24v2hy67/SOURCES/titotestpkg-0.0.1/':
Operation not permitted
Even when changing the debug line to just
debug('', 'ls -l /')
it still fails. Let's just use `os.listdir`

Fix travis CI tests for Fedora Rawhide

---

src/tito/builder/main.py
src/tito/common.py

Fix: #311
Supersedes: #313
The `get_project_name` function is called in an early phase when
the temporary `SOURCES` directory for a current build doesn't exist yet.
Therefore as a little workaround, we set `_sourcedir` to an upstream
directory containing the package spec file.
Defining a custom `_sourcedir` (and therefore not using
`~/rpmbuild/SOURCES`) shouldn't be a problem because tito builds
should not depend on anything outside of the upstream git repository.
The use-case described in PR#313 works as expected.
SOURCE1: somecool.macros
%include %{SOURCE1}
For multi-spec projects, where you have e.g
.
├── foo
│   ├── foo.spec
├── bar
│   ├── bar.spec
It is possible to include the common macros from a parent (or some
other) directory by having a symlink.
cd foo
ln -s ../somecool.macros …

Allow including macros through SourceX

---

.tito/releasers.conf
HACKING.md
README.md
doc/index.md
mkdocs.yml
setup.py
tito.spec

We collectively decided to move tito upstream from https://github.com/dgoodwin/tito to https://github.com/rpm-software-management/tito

Move tito under rpm-software-management namespace

---

src/tito/builder/main.py

Fix #331
Do not specify `_source_filedigest_algorithm`
and `_binary_filedigest_algorithm` anymore
EPEL5 did understand only MD5 checksums but since it is EOLed and
newer releases know SHA, we can probably safely remove it.

Do not specify file digest algorithms

---

src/tito/cli.py

Fix #338
We want to use as few bash commands instead of python functions as
possible anyway, but this rewrite fixes #338

Use mkpath instead of running mkdir -p command

---

src/tito/cli.py

Fix #158
As a consequence we can easily print a different message when running
`tito init` an already initialized tito project.
I am basing this PR on a commit from PR #368 because I wanted to avoid dealing with merge conflicts. Please make sure that #368 gets merged first.

Separate .tito directory creation from tito.props file creation

---

src/tito/release/main.py
test/unit/__init__.py
test/unit/releaser_tests.py

Fix #364
Previously all non-yes input was considered to be "no". Which is not
what we typically want. There should be expected "yes" inputs, expected
"no" inputs and everything else should be considered to be an uknown
input and should be treated this way.
I think that printing an error for unknown input is too verbose and have
no added value. Simply repeating the question is the way to go here:
Do you wish to proceed with commit? [y/n] foo
Do you wish to proceed with commit? [y/n] y
Proceeding with commit.

Make yes or no input less aggressive

---

src/tito/builder/main.py

* Extra source file can be copied/moved by some other tool
* When the source file already exists in destination path, then
do not try to copy it once again
* This issue was observed, when we tried to build
subscription-manager on Fedora 32 using tito

When extra source file exist, then do not copy it

---

src/tito/distributionbuilder.py

* When tito is installed using pip, then generate-patches is
installed into the `~/.local/bin` directory and the absolute
path cannot work

Do not use absolute path to generate-patches.pl script

---

src/tito/builder/main.py
src/tito/compat.py

Fix #387
A build with a remote URL in its `SourceX` will work only with
%_disable_source_fetch 0
macro defined. It can be done either globally via `~/.rpmmacros` or by
using tito with following parameter
--rpmbuild-options="--define '%_disable_source_fetch 0'"
IMHO this macro should be set by default but we should also introduce
a switch to turn it off (like e.g. Mock or Copr do). Since it is not
related to fixing #387, I am not doing it in this commit.

Fix copy_extra_sources for remote URLs

---

src/tito/builder/main.py

... by ignoring spectool warnings (and therefore fixing the assumption that each line is a `SourceX` file) and by not trying to copy nonexisting files.

Make copy_extra_sources method more foolproof

---

test/functional/build_gitannex_tests.py
test/functional/fetch_tests.py
test/functional/fixture.py
test/functional/specs/extsrc-2.spec
test/functional/specs/extsrc-3.spec

See RHBZ 1784688
We are using unversioned python macros, such as `%__python` and
`%python_sitelib` which are not supported in Fedora rawhide
anymore. Instead, we should use `%__python3` and `%python3_sitelib`.

Make tests working on systems without non-versioned python macros

---

src/tito/cli.py
tito.props.5.asciidoc

Complements PR #407
Every other `tito.props` config option uses underscores instead of
dashes, so let's preserve this convention.
Also describing it in the manpage.

Rename and document the tito.props option for fetching sources

---

src/tito/common.py
src/tito/release/distgit.py
src/tito/tagger/main.py

I use two different email addresses for git config, depending on what
kind of project it is going on. I use my personal email address for
public community projects and my work email address for internal
repositories.
Let's say my global config is my personal address
$ git config --get --global user.email
frostyx@email.cz
And that I am working on an internal project, therefore I set
git config user.email "jkadlcik@redhat.com"
Once I run `tito release internal`, I would like all changes to be
commited with my work address, i.e. I would like the local git user
config to be considered. This commit fixes that.

Consider the current project git config when releasing to DistGit

---

src/tito/builder/main.py
src/tito/compat.py
src/tito/release/distgit.py

Previously only 'tito build --srpm|--rpm' worked well with fetch_sources
where we rely on RPM's (rpmbuild) built-in download mechanism.  It did
not work well with 'tito release' and DistGit releasers, though.
The thing is that we don't use rpmbuild at all while doing DistGit
releases BUT we still want those files to be (a) downloaded to
%_sourcedir and then (b) uploaded to DistGit lookaside cache.  Because
we did not download those files before, every extra source file was
entirely ignored, or even worse, if the file was already uploaded in
the target lookaside cache, the file was removed from sources.
This bitten us during 'copr-backend' releases several times, and starts
being painful in 'resalloc-aws' releases, too.

DistGitReleasers: don't nuke external sources with fetch_sources

---

src/tito/release/distgit.py

- The original change made the assumption that the git_branches[0]
is the actual branch name that we are on, but that was incorrect.

Revert 45d431ad149cb33e2462a990c4c4f29e6bb2bb7e

---

src/tito/release/distgit.py

With @xsuchy we discovered that when doing `tito release`, into Fedora DistGit, then .patch files are being uploaded to the lookaside cache. That is not expected behavior, we should commit them to git only.

Don't upload patches to the lookaside cache

---

src/tito/release/main.py

https://packit.dev/docs/configuration/
packit.yaml can be used in dist-git for pull-from-upstream and for creating builds, or bodhi updates

do not overwrite packit.yaml and its variants

---

src/tito/builder/submodule_aware_builder.py

Submodules may contain other submodules. Do process and add those to the source tar.

---

src/tito/builder/main.py
src/tito/distributionbuilder.py

I started seeing this deprecation warning in `tito build ...` output.
RPM build warnings:
%patchN is deprecated (1 usages found), use %patch N (or %patch -P N)

Fix UpstreamBuilder deprecation warning

---

src/tito/builder/main.py

Also fix some spelling errors
fixes #463

Will now copy both source files and patch files declared in the spec

---

pylintrc
src/tito/builder/main.py
src/tito/cli.py

Allow tito build without .tito directory

---

src/tito/builder/fetch.py
src/tito/common.py
src/tito/tagger/cargobump.py
src/tito/tagger/main.py
src/tito/tagger/rheltagger.py
src/tito/tagger/susetagger.py
src/tito/tar.py

I am fixing the following syntax warnings and more.
/home/jkadlcik/git/tito/src/tito/common.py:81: SyntaxWarning: invalid escape sequence '\d'
source_pattern = re.compile('^Source\d+?:\s*(.*)')
/home/jkadlcik/git/tito/src/tito/common.py:732: SyntaxWarning: invalid escape sequence '\s'
ver_regex = re.compile("(\s*)(version)(\s*)(=)(\s*)(['\"])(.*)(['\"])(.*)",
/home/jkadlcik/git/tito/src/tito/tar.py:187: SyntaxWarning: invalid escape sequence '\d'
field_size = int(re.match('(\d+)', member_template).group(1)) - 1

Use raw strings for regex patterns

---

src/tito/builder/main.py
src/tito/cli.py

Fix #472
Now, it is possible to build packages without using any parameters.
```
$ tito --srpm --test
Creating output directory: /tmp/tito
WARNING: Tito project wasn't initialized,using the default configuration
WARNING: Consider `tito init' or the `--without-init' parameter to silent the warnings
WARNING: Unable to lookup latest package tag, building untagged test project
WARNING: .tito/packages/tito doesn't exist in git, using current directory
Building package [tito-0.6.24-1]
Wrote: /tmp/tito/tito-git-9.1e9ec0b.tar.gz
setting SOURCE_DATE_EPOCH=1688774400
Wrote: /tmp/tito/tito-0.6.24-1.git.9.1e9ec0b.fc39.src.rpm
```
To silence the warnings, it is possible to use the `--without-init` parameter
```
$ tito build --srpm --test --without-init
Creating output directory: /tmp/tito
Building …
```

Building in non-initialized project without explicit parameter

---

src/tito/release/main.py

Fix #481
See also https://github.com/rpm-software-management/mock/pull/1223
As a reproducer, I used the following releaser:
[yum]
releaser = tito.release.YumRepoReleaser
builder = tito.builder.Builder
srpm_disttag = fc39
rsync = /tmp/tito/yum-repo
and then did `tito release yum`.

Use rpm.ds instead of deprecated hdr.dsFromHeader

---

src/tito/builder/main.py

Creating output directory: /tmp/tito
src/tito/builder/main.py:871: SyntaxWarning: invalid escape sequence '\d'
patch_pattern = re.compile('^Patch(\d+):')
src/tito/builder/main.py:872: SyntaxWarning: invalid escape sequence '\d'
source_pattern = re.compile('^Source(\d+)?:')
Building package [tito-0.6.25-1]
Wrote: /tmp/tito/tito-git-2.909184d.tar.gz

Fix a runtime SyntaxWarning with Python 3.12

---

tito

This makes executing of Tito-from-Git a bit more convenient.

<gitroot>/tito wrapper

---

src/tito/tagger/main.py

Remove redundant slash from a regex

---

src/tito/builder/main.py
src/tito/common.py
tito.props.5.asciidoc

If configured like
$ cat .tito/tito.props
[buildconfig]
test_version_suffix = .tito.git
The `tito build --test ...` NEVRA is always higher than the NEVRA of released RPMs.
Fixes: #460

New config option `buildconfig.test_version_suffix`

---

pylintrc

************* Module pylintrc
pylintrc:1:0: F0011: error while parsing the configuration: File contains no section

Fix pylintrc & sync with Mock's one

---

src/tito/builder/submodule_aware_builder.py

Recent builds on copr started failing for rpms using submodule aware builders, see logs below. The root cause for the issue was the presence of an empty `.gitmodules` file in a submodule. The recursion logic currently only checks if the file exists, if it does, tries to fetch the paths using the `git config --file .gitmodules --get-regexp path` command. Which exits with status code `1` when the `.gitmodules` file is empty.
I have tried to work around this issue by deferring the logic of identifying all nested submodules to `git submodule status --recursive` instead. Which allows for a less complex handling within tito. Ideally, I reckon this could even be simplified further by use of either the `git submodules foreach 'git archive ...'` command or  `git ls-files --recurse-submodules` and …

builder: defer submodule detection to git
