rpm-software-management/tito

tito.8.asciidoc

Add tito tag --use-version argument to man page

---

README.md

Some people may want something more like rpmdistro-gitoverlay for
example.

README.md: Also link to Fedora wiki page collection of these tools

---

src/tito/builder/main.py
src/tito/common.py

See #233 
Can you please do review of this code @dgoodwin ?
Thank you

Use Dnf or Yum over Rpm when it is possible

---

share/tito_completion.sh
src/tito/cli.py
tito.8.asciidoc

fixes #29 - remove --list-tags and --only-tags

---

src/tito/common.py

253 - print cmd info when --debug is supplied

---

.travis.yml

@dgoodwin once the testing is enabled in your repo config and this merges, we should hopefully see the tests run on PRs

Add a Travis CI manifest

---

src/tito/common.py

Reverts dgoodwin/tito#286
We can re-add once someone can figure out what's up.

Revert "use LC_ALL=C.UTF-8 rather than plain C"

---

src/tito/builder/main.py
src/tito/common.py

Currently when building RPMs or SRPMs with MockBuilder, tito will not print the
output from mock. This makes diagnosis harder especially in CI
environments.
This PR will do the following changes:
1. If `--quiet` option is not specified, `run_command_print` will be used to
run the `mock` or `rpmbuild` command. Otherwise we will continue to use
`run_command`.
2. `run_command_print` will print error message when an error happens, like what `run_command`
does.

Print mock output when building with MockBuilder

---

src/tito/builder/main.py

tito build --test --rpm -i Traceback on Fedora 31

---

src/tito/common.py

The existing implementation of `run_command_print` uses `shlex.split`
to split command line arguments into an array, but it doesn't handle
wildcards like `run_command`. This breaks Mock build because of failure
of copying generated RPMs.
This PR also adds `print_on_success` argument and unify the behavior of
error handling.
Reproduction:
``` bash
$ tito build --test --rpm --output=artifacts/el6 --builder=tito.builder.MockBuilder --arg=mock=eng-rhel-6-candidate-x86_64
...
INFO: Results and/or logs in: /var/lib/mock/ERROR: Error running command: cp -v /home/fedora/jenkins/workspace/rcm-pulp-rpm-package/artifacts/el6/rpmbuild-pulp-rpm4f6rzL/mockoutput/*.rpm /home/fedora/jenkins/workspace/rcm-pulp-rpm-package/artifacts/el6
```

Bugfix: run_command_print should behave similar to run_command

---

.tito/releasers.conf
doc/maintenance.md

So we can be sure that every maintainer does it the same way.

Describe how to release tito

---

README.md

mention the #tito irc channel in the readme

---

.tito/templates/__init__.py.tpl
.tito/tito.props
src/tito/cli.py

Implement --version parameter

---

src/tito/tagger/main.py
test/functional/fetch_tests.py
test/unit/__init__.py
test/unit/tagger_tests.py
tito.props.5.asciidoc

Add a possibility to have full datetime entries in changelog

---

README.md

Add a list of projects using tito

---

src/tito/builder/main.py

Fix #367
We accidentally introduced `copy_extra_sources` method as a part of
`BuilderBase` class. Which wouldn't be a problem, except for the fact
that its implementation uses properties, that are not a part of
that class but are rather defined in **some** of its descendats.
Let's define this method only abstractly and let more specific
builder classes to provide their own implementation if it makes
sense for them.

Fix copy_extra_sources for alternative builders

---

src/tito/release/distgit.py

Related to https://pagure.io/copr/copr/pull-request/1397

FedoraGitReleaser: upload extra sources to lookaside cache

---

src/tito/release/main.py

Use --no-rebuild-srpm for scratch builds in KojiReleaser

---

src/tito/builder/main.py

Drop unused urllib.request import

---

README.md
doc/index.md

http://frostyx.cz/posts/building-rhel-packages-with-tito

Add 'Building RHEL packages with Tito' as external doc

---

doc/builders.md
src/tito/builder/main.py
src/tito/cli.py
tito.props.5.asciidoc

Fix and document MockBuilder

---

src/tito/builder/submodule_aware_builder.py

- Fix for issue #413
- Fix for issue #414

Fixes for submodule_aware_builder

---

src/tito/compat.py

Fix python2 urlretrieve import

---

tito.spec

https://fedoraproject.org/wiki/Changes/SPDX_Licenses_Phase_1

use spdx license

---

.github/workflows/fedora-tox.yml
.github/workflows/python-diff-lint.yml
.github/workflows/shell-diff-lint.yml

- enable differential PyLint checker
- enable differential ShellCheck (there's a bash script in this repo)
- enable Fedora test matrix

automation: some useful pre-commit workflows

---

.github/workflows/python-diff-lint.yml
.packit.yml
README.md

Into https://copr.fedorainfracloud.org/coprs/g/rpm-software-management/tito/

automation: automatically build pre-release RPMs

---

.github/workflows/fedora-tox.yml

We're going to remove the old branch soon.

Switch tox-github-action from master to main branch

---

src/tito/builder/submodule_aware_builder.py

Replace `submodule--helper list` with `git config --get-regexp`

---

setup.py

Fix the setup.py license according to tito.spec

---

doc/builders.md

Show how to specify additional mock parameters

---

hacking/runtests.sh
src/tito/builder/submodule_aware_builder.py
src/tito/common.py
src/tito/tar.py
test/unit/pep8_tests.py

I was running runtests.py and found some issues

---

doc/index.md

document how to automate bodhi updates

---

doc/maintenance.md
tito.spec

Bump the ENVRA built directly from git master branch

---

.packit.yml

Complements: #483
Relates: #480

packit: generate tarball by tito, read Version from spec

---

src/tito/release/distgit.py
tito.spec

Support branch aliases in releasers

---

src/tito/cli.py

Fixup after 68d8b21
Obsoletes PR #487

Fix traceback related to undefined variable

---

src/tito/release/distgit.py

Whatever the alias order, release into rawhide first

---

.github/workflows/fedora-tox.yml
.github/workflows/python-diff-lint.yml
.github/workflows/shell-diff-lint.yml
.packit.yml
HACKING.md
doc/index.md
doc/maintenance.md
tito

Rename master branch to main

---

tito.spec

https://fedoraproject.org/wiki/Changes/ChangeToGitCore

depend on git-core instead of git
